## Diagnostic dashboard app generator

library(dplyr)
library(sf)

orderly::orderly_shared_resource('District edited Jan 2021')
orderly::orderly_dependency(
  "create_diagnostic_dashboard",
  quote(latest()),
  c(
    "council_summary.rds" = "council_summary.rds",
    "council_timeseries.rds" = "council_timeseries.rds",
    "prevalence_comparison.rds" = "prevalence_comparison.rds",
    "council_mcmc_diagnostics.rds" = "council_mcmc_diagnostics.rds",
    "diagnostic_plot_index.rds" = "diagnostic_plot_index.rds"
  )
)

tryCatch({
  orderly::orderly_dependency(
    "create_diagnostic_dashboard",
    quote(latest()),
    c("diagnostic_plots/" = "diagnostic_plots")
  )
}, error = function(e) {
  message("diagnostic_plots not available in latest run; continuing without plots.")
})

# Dependency files are copied into the working directory by orderly
council_summary <- readRDS('council_summary.rds')
council_timeseries <- readRDS('council_timeseries.rds')
prevalence_comparison <- readRDS('prevalence_comparison.rds')
plot_index <- readRDS('diagnostic_plot_index.rds')

# Load council boundaries
councils_sf <- sf::st_read(
  'District edited Jan 2021/District edited Jan 2021.shp',
  quiet = TRUE
) %>%
  dplyr::rename(council = DHIS2_Dist)

# Ensure WGS84
if (!sf::st_is_longlat(councils_sf)) {
  councils_sf <- sf::st_transform(councils_sf, 4326)
}

app_code <- c(
  "library(shiny)",
  "library(dplyr)",
  "library(leaflet)",
  "library(plotly)",
  "library(sf)",
  "",
  "app_dir <- getwd()",
  "app_file <- tryCatch(sys.frame(1)$ofile, error = function(e) NULL)",
  "if (!is.null(app_file) && nzchar(app_file)) {",
  "  app_dir <- dirname(normalizePath(app_file, winslash = '/', mustWork = FALSE))",
  "}",
  "council_summary <- readRDS(file.path(app_dir, 'council_summary.rds'))",
  "council_timeseries <- readRDS(file.path(app_dir, 'council_timeseries.rds'))",
  "prevalence_comparison <- readRDS(file.path(app_dir, 'prevalence_comparison.rds'))",
  "plot_index <- readRDS(file.path(app_dir, 'diagnostic_plot_index.rds'))",
  "",
  "councils_sf <- sf::st_read('District edited Jan 2021/District edited Jan 2021.shp', quiet = TRUE)",
  "councils_sf <- dplyr::rename(councils_sf, council = DHIS2_Dist)",
  "if (!sf::st_is_longlat(councils_sf)) councils_sf <- sf::st_transform(councils_sf, 4326)",
  "",
  "metric_choices <- c(",
  "  'RMSE' = 'rmse',",
  "  'MAE' = 'mae',",
  "  'Correlation' = 'correlation',",
  "  'Acceptance (min)' = 'acceptance_min',",
  "  'ESS (min)' = 'ess_min'",
  ")",
  "eir_choices <- c('EIR'='EIR','betaa'='betaa','eff_moz_pop'='eff_moz_pop',",
  "                 'moz2human_ratio'='moz2human_ratio','spz_rate'='spz_rate')",
  "",
  "ui <- fluidPage(",
  "  titlePanel('PMCMC Diagnostics Dashboard'),",
  "  tabsetPanel(id = 'main_tabs',",
  "    tabPanel('Overview',",
  "      fluidRow(",
  "        column(8,",
  "          selectInput('metric', 'Map metric', choices = metric_choices, selected = 'correlation'),",
  "          leafletOutput('council_map', height = 600)",
  "        ),",
  "        column(4,",
  "          div(style='margin-top: 40px;',",
  "              textOutput('summary_text')),",
  "          plotlyOutput('metric_scatter', height = 450)",
  "        )",
  "      )",
  "    ),",
  "    tabPanel('Council',",
  "      fluidRow(",
  "        column(4,",
  "          selectInput('council_select', 'Select council',",
  "                      choices = sort(unique(council_summary$council)))",
  "        ),",
  "        column(8,",
  "          selectInput('eir_metric', 'EIR metric', choices = eir_choices, selected = 'EIR')",
  "        )",
  "      ),",
  "      fluidRow(",
  "        column(12, plotlyOutput('prev_ts', height = 250))",
  "      ),",
  "      fluidRow(",
  "        column(12, plotlyOutput('clininc_ts', height = 250))",
  "      ),",
  "      fluidRow(",
  "        column(12, plotlyOutput('eir_ts', height = 250))",
  "      )",
  "    ),",
  "    tabPanel('Diagnostics',",
  "      fluidRow(",
  "        column(4,",
  "          selectInput('diag_council', 'Select council',",
  "                      choices = sort(unique(council_summary$council)))",
  "        ),",
  "        column(8,",
  "          plotlyOutput('obs_fit_scatter', height = 350)",
  "        )",
  "      ),",
  "      fluidRow(",
  "        column(12, plotlyOutput('mcmc_diag_scatter', height = 450))",
  "      )",
  "    )",
  "  )",
  ")",
  "",
  "server <- function(input, output, session) {",
  "  output$summary_text <- renderText({",
  "    total <- nrow(council_summary)",
  "    has_results <- sum(council_summary$has_results, na.rm = TRUE)",
  "    avg_rmse <- mean(council_summary$rmse, na.rm = TRUE)",
  "    paste0('Councils with results: ', has_results, ' / ', total,",
  "           ' | Avg RMSE: ', round(avg_rmse, 4))",
  "  })",
  "",
  "  output$council_map <- renderLeaflet({",
  "    metric <- input$metric",
  "    map_df <- councils_sf %>%",
  "      left_join(council_summary, by = 'council')",
  "",
  "    pal <- colorNumeric('YlOrRd',",
  "                        domain = map_df[[metric]], na.color = '#555555')",
  "",
  "    legend_values <- map_df[[metric]]",
  "    legend_values <- legend_values[is.finite(legend_values)]",
  "    legend_breaks <- unique(pretty(legend_values, n = 5))",
  "    if (length(legend_breaks) < 2 && length(legend_values) > 0) {",
  "      legend_breaks <- range(legend_values)",
  "    }",
  "    legend_breaks <- rev(legend_breaks)",
  "    legend_colors <- pal(legend_breaks)",
  "    legend_labels <- format(legend_breaks, trim = TRUE)",
  "",
  "    leaflet(map_df) %>%",
  "      addProviderTiles('CartoDB.Positron') %>%",
  "      addPolygons(",
  "        fillColor = ~pal(get(metric)),",
  "        fillOpacity = 0.7,",
  "        color = '#444444',",
  "        weight = 1,",
  "        layerId = ~council,",
  "        label = ~paste0(council, ': ',",
  "                        ifelse(is.na(get(metric)), 'NA',",
  "                               round(get(metric), 4)))",
  "      ) %>%",
  "      addLegend(colors = legend_colors, labels = legend_labels,",
  "                title = metric, position = 'bottomleft', opacity = 1)",
  "  })",
  "",
  "  output$metric_scatter <- renderPlotly({",
  "    metric <- input$metric",
  "    df <- council_summary %>% filter(!is.na(mean_obs_prevalence))",
  "    plot_ly(df, x = ~mean_obs_prevalence, y = df[[metric]],",
  "            type = 'scatter', mode = 'markers',",
  "            text = ~council) %>%",
  "      layout(xaxis = list(title = 'Mean observed prevalence'),",
  "             yaxis = list(title = metric))",
  "  })",
  "",
  "  observeEvent(input$council_map_shape_click, {",
  "    click <- input$council_map_shape_click",
  "    if (is.null(click$id)) return()",
  "    updateSelectInput(session, 'council_select', selected = click$id)",
  "    updateSelectInput(session, 'diag_council', selected = click$id)",
  "    updateTabsetPanel(session, 'main_tabs', selected = 'Council')",
  "  })",
  "",
  "  observeEvent(input$council_select, {",
  "    if (!identical(input$diag_council, input$council_select)) {",
  "      updateSelectInput(session, 'diag_council', selected = input$council_select)",
  "    }",
  "  }, ignoreInit = TRUE)",
  "",
  "  observeEvent(input$diag_council, {",
  "    if (!identical(input$council_select, input$diag_council)) {",
  "      updateSelectInput(session, 'council_select', selected = input$diag_council)",
  "    }",
  "  }, ignoreInit = TRUE)",
  "",
  "  output$prev_ts <- renderPlotly({",
  "    council <- input$council_select",
  "    df <- council_timeseries %>% filter(council == !!council, measure == 'prev_anc_all')",
  "    fitted <- df %>% filter(series == 'fitted')",
  "    observed <- df %>% filter(series == 'observed')",
  "",
  "    p <- plot_ly()",
  "    if (nrow(fitted) > 0) {",
  "      p <- p %>% add_ribbons(x = fitted$month, ymin = fitted$lower, ymax = fitted$upper,",
  "                             line = list(color = 'transparent'),",
  "                             fillcolor = 'rgba(31,119,180,0.2)', name = 'Fitted 95% CI') %>%",
  "        add_lines(x = fitted$month, y = fitted$value, name = 'Fitted')",
  "    }",
  "    if (nrow(observed) > 0) {",
  "      p <- p %>% add_markers(x = observed$month, y = observed$value, name = 'Observed')",
  "    }",
  "    p %>% layout(title = 'Observed vs Fitted Prevalence (ANC)',",
  "                 xaxis = list(title = '', range = list(2014, 2025)),",
  "                 yaxis = list(title = 'Prevalence'),",
  "                 legend = list(orientation = 'h', x = 0.5, xanchor = 'center', y = -0.2),",
  "                 margin = list(b = 70))",
  "  })",
  "",
  "  output$clininc_ts <- renderPlotly({",
  "    council <- input$council_select",
  "    df <- council_timeseries %>% filter(council == !!council, measure == 'clininc_all', series == 'fitted')",
  "    plot_ly(df, x = ~month, y = ~value, type = 'scatter', mode = 'lines', name = 'Clinical incidence') %>%",
  "      layout(title = 'Clinical Incidence (Fitted)',",
  "             xaxis = list(title = '', range = list(2014, 2025)),",
  "             yaxis = list(title = 'Incidence'))",
  "  })",
  "",
  "  output$eir_ts <- renderPlotly({",
  "    council <- input$council_select",
  "    metric <- input$eir_metric",
  "    df <- council_timeseries %>% filter(council == !!council, measure == !!metric, series == 'fitted')",
  "    plot_ly(df, x = ~month, y = ~value, type = 'scatter', mode = 'lines', name = metric) %>%",
  "      layout(title = paste0(metric, ' (Fitted)'),",
  "             xaxis = list(title = '', range = list(2014, 2025)),",
  "             yaxis = list(title = metric))",
  "  })",
  "",
  "  output$obs_fit_scatter <- renderPlotly({",
  "    council <- input$diag_council",
  "    df <- prevalence_comparison %>% filter(council == !!council)",
  "    plot_ly(df, x = ~obs_prevalence, y = ~fitted_prevalence,",
  "            type = 'scatter', mode = 'markers') %>%",
  "      layout(title = 'Observed vs Fitted Prevalence',",
  "             xaxis = list(title = 'Observed'),",
  "             yaxis = list(title = 'Fitted'))",
  "  })",
  "",
  "  output$mcmc_diag_scatter <- renderPlotly({",
  "    council <- input$diag_council",
  "    df <- council_summary %>%",
  "      filter(!is.na(acceptance_min), !is.na(ess_min))",
  "    selected <- df %>% filter(council == !!council)",
  "",
  "    p <- plot_ly(df, x = ~acceptance_min, y = ~ess_min,",
  "                type = 'scatter', mode = 'markers',",
  "                text = ~council, hoverinfo = 'text')",
  "    if (nrow(selected) > 0) {",
  "      p <- p %>% add_markers(data = selected, x = ~acceptance_min, y = ~ess_min,",
  "                             marker = list(size = 12, color = '#d62728'),",
  "                             name = 'Selected', hoverinfo = 'text')",
  "    }",
  "    p %>% layout(title = 'Acceptance vs ESS (min)',",
  "                xaxis = list(title = 'Acceptance rate (min)'),",
  "                yaxis = list(title = 'ESS (min)'))",
  "  })",
  "}",
  "",
  "shinyApp(ui, server)"
)

writeLines(app_code, 'diag_dash_app.R')
